#ifndef CHAR_TYPE_H_INCLUDED
#define CHAR_TYPE_H_INCLUDED

typedef enum CHAR_TYPE
{
	CHAR_TYPE_LITERAL = 0x1,
	CHAR_TYPE_SYMBOL = 0x2,
	CHAR_TYPE_MASK = 0x3,
} CHAR_TYPE;

#endif//CHAR_TYPE_H_INCLUDED

